# ============================== Filebeat inputs ===============================
filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /data-from-cloud/*-insights-logs-functionapplogs/resourceId=/SUBSCRIPTIONS/*/RESOURCEGROUPS/*/PROVIDERS/MICROSOFT.WEB/SITES/*/y=*/m=*/d=*/h=*/m=*/*.json
  fields:
    log_type: "azure-function-app"
  ignore_older: 5m
  fields_under_root: true
# ================================== Outputs ===================================
# ---------------------------- Elasticsearch Output ----------------------------
# ------------------------------ Logstash Output -------------------------------
output.logstash:
  hosts: ["t-elk:1060"]
  indices:
    - index: "azure-function-app"
      when.contains:
        log_type: "azure-function-app"
# ================================= Processors =================================
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
# ================================== Logging ===================================
logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat-azure-function-app.log
  keepfiles: 1
  permissions: 0644