# ============================== Filebeat inputs ===============================
filebeat.inputs:
- type: log
  enabled: true
  paths:
    # - /var/log/squid/access.log
    - /data-to-local/my/azure-squid/proxy-tls/access.log
  fields:
    log_type: "azure-squid"
  fields_under_root: true
# ================================== Outputs ===================================
# ---------------------------- Elasticsearch Output ----------------------------
# ------------------------------ Logstash Output -------------------------------
output.logstash:
  hosts: ["t-elk:1400"]
  indices:
    - index: "azure-squid"
      when.contains:
        log_type: "azure-squid"
    - index: "azure-squid-tls"
      when.contains:
        log_type: "azure-squid-tls"
    - index: "azure-squid-sslbypass"
      when.contains:
        log_type: "azure-squid-sslbypass"
# ================================= Processors =================================
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
# ================================== Logging ===================================
logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat-azure-squid.log
  keepfiles: 1
  permissions: 0644