# ============================== Filebeat inputs ===============================
filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /data-to-local/*-insights-logs-applicationgatewayaccesslog/resourceId=/SUBSCRIPTIONS/*/RESOURCEGROUPS/*/PROVIDERS/MICROSOFT.NETWORK/APPLICATIONGATEWAYS/*/y=*/m=*/d=*/h=*/m=*/*.json
  fields:
    log_type: "azure-waf-access"
  fields_under_root: true
# ================================== Outputs ===================================
# ---------------------------- Elasticsearch Output ----------------------------
# ------------------------------ Logstash Output -------------------------------
output.logstash:
  hosts: ["t-elk:1020"]
  indices:
    - index: "azure-waf-access"
      when.contains:
        log_type: "azure-waf-access"
# ================================= Processors =================================
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
# ================================== Logging ===================================
logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat-azure-waf-access.log
  keepfiles: 1
  permissions: 0644