# ============================== Filebeat inputs ===============================
filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /data-from-cloud/*-insights-logs-containerregistryloginevents/resourceId=/SUBSCRIPTIONS/*/RESOURCEGROUPS/*/PROVIDERS/MICROSOFT.CONTAINERREGISTRY/REGISTRIES/*/y=*/m=*/d=*/h=*/m=*/*.json
  fields:
    log_type: "azure-cr-login"
  ignore_older: 5m
  fields_under_root: true
- type: log
  enabled: true
  paths:
    - /data-from-cloud/*-insights-logs-containerregistryrepositoryevents/resourceId=/SUBSCRIPTIONS/*/RESOURCEGROUPS/*/PROVIDERS/MICROSOFT.CONTAINERREGISTRY/REGISTRIES/*/y=*/m=*/d=*/h=*/m=*/*.json
  fields:
    log_type: "azure-cr-repository"
  ignore_older: 5m
  fields_under_root: true
# ================================== Outputs ===================================
# ---------------------------- Elasticsearch Output ----------------------------
# ------------------------------ Logstash Output -------------------------------
output.logstash:
  hosts: ["t-elk:1070"]
  indices:
    - index: "azure-cr-login"
      when.contains:
        log_type: "azure-cr-login"
    - index: "azure-cr-repository"
      when.contains:
        log_type: "azure-cr-repository"
# ================================= Processors =================================
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
# ================================== Logging ===================================
logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat-azure-cr.log
  keepfiles: 1
  permissions: 0644