# ============================== Filebeat inputs ===============================
filebeat.inputs:
- type: log
  enabled: true
  paths:
    # - /var/log/squid/access.log
    - /data-to-local/my/azure-squid/proxy-tls/access.log
  fields:
    log_type: "azure-squid-tls"
  # Filebeat starts reading new files at the end of each file
  tail_files: true
  # Filebeat ignores any files that were modified before the 1 min
  ignore_older: 1m
  fields_under_root: true
- type: log
  enabled: true
  paths:
    - /data-from-cloud/eda-azure-squid/proxy-sslbypass/access.log
  fields:
    log_type: "azure-squid-sslbypass"
  tail_files: true
  ignore_older: 1m
  fields_under_root: true
# ================================== Outputs ===================================
# ---------------------------- Elasticsearch Output ----------------------------
# ------------------------------ Logstash Output -------------------------------
output.logstash:
  hosts: ["t-elk:1400"]
  indices:
    - index: "azure-squid"
      when.contains:
        log_type: "azure-squid"
    - index: "azure-squid-tls"
      when.contains:
        log_type: "azure-squid-tls"
    - index: "azure-squid-sslbypass"
      when.contains:
        log_type: "azure-squid-sslbypass"
# ================================= Processors =================================
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
# ================================== Logging ===================================
logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat-azure-squid.log
  keepfiles: 1
  permissions: 0644