# ============================== Filebeat inputs ===============================
filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /data-to-local/*-am-auditlogs/WorkspaceResourceId=/subscriptions/*/resourcegroups/*/providers/microsoft.operationalinsights/workspaces/*/y=*/m=*/d=*/h=*/m=*/*.json
  fields:
    log_type: "aad-audit"
  fields_under_root: true
# ================================== Outputs ===================================
# ---------------------------- Elasticsearch Output ----------------------------
# ------------------------------ Logstash Output -------------------------------
output.logstash:
  hosts: ["t-elk:1100"]
  indices:
    - index: "aad-audit"
      when.contains:
        log_type: "aad-audit"
# ================================= Processors =================================
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
# ================================== Logging ===================================
logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat-aad-audit.log
  keepfiles: 1
  permissions: 0644